version: '3.1'
services:
  mySQL:
    image: mysql:latest
    ports:
    - '3306:3306'
    volumes:
    - ./schema:/docker-entrypoint-initdb.d:ro
    environment:
    - MYSQL_DATABASE=app
    - MYSQL_USER=app
    - MYSQL_PASSWORD=pass
    - MYSQL_RANDOM_ROOT_PASSWORD=yes